/**
 * Factory schema — the f_* tables and factory_* RPC functions.
 *
 * The Kalvex factory (market-researcher) shares THIS database: its f_* tables
 * live beside sinopebase's own tables, and its atomic operations run as
 * Postgres functions over PostgREST /rpc (supabase-js contract). The factory
 * keeps all policy math (trust deltas, clamps, approval decisions) in
 * TypeScript and passes computed values in — these functions are thin
 * transactional data moves, never business rules.
 *
 * RLS: `anon`/`authenticated` get nothing. `service_role` reads and writes
 * everything (the factory connects with its service key). `sinopebase_app`
 * may SELECT (admin browsing). The tables' owner bypasses RLS.
 *
 * Layer 5 — depends on ~/migrations/types.
 */

import type { MigrationDB } from './types.ts'

// Typed OUT columns (RETURNS TABLE requires name+type); RETURNING * matches
// f_messages' column order exactly, so queries can use SELECT/RETURNING *.
const MESSAGE_COLUMNS = `
  id BIGINT, agent TEXT, kind TEXT, contact TEXT, copy TEXT, original_copy TEXT,
  context TEXT, platform TEXT, status TEXT, scheduled_at BIGINT, sent_at BIGINT,
  sampled BOOLEAN
`

export async function up(db: MigrationDB): Promise<void> {
  await db.raw(`
    -- ── f_* tables (DDL mirrored from the factory's migrations) ─────────────
    CREATE TABLE IF NOT EXISTS f_agents (
      name TEXT PRIMARY KEY,
      trust INTEGER NOT NULL DEFAULT 0 CHECK (trust BETWEEN 0 AND 100),
      approved_count INTEGER NOT NULL DEFAULT 0,
      internal BOOLEAN NOT NULL DEFAULT false,
      parent TEXT
    );
    CREATE TABLE IF NOT EXISTS f_messages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      agent TEXT NOT NULL REFERENCES f_agents(name),
      kind TEXT NOT NULL,
      contact TEXT NOT NULL,
      copy TEXT NOT NULL,
      original_copy TEXT NOT NULL,
      context TEXT NOT NULL DEFAULT '',
      platform TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'scheduled', 'sent')),
      scheduled_at BIGINT,
      sent_at BIGINT,
      sampled BOOLEAN NOT NULL DEFAULT false
    );
    CREATE TABLE IF NOT EXISTS f_andon_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trigger TEXT NOT NULL,
      detail TEXT,
      ts BIGINT NOT NULL DEFAULT 0,
      decision TEXT NOT NULL DEFAULT '',
      snapshot TEXT NOT NULL DEFAULT ''
    );
    CREATE TABLE IF NOT EXISTS f_state (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS f_metrics (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      kind TEXT NOT NULL CHECK (kind IN ('meeting_booked', 'thesis_confirm', 'thesis_reject', 'sentiment', 'sent', 'sent_dryrun', 'correction', 'rejection', 'judge_provenance', 'judge_contradiction', 'judge_robotic', 'judge_rejected', 'reply')),
      agent TEXT,
      contact TEXT,
      value REAL NOT NULL DEFAULT 0,
      ts BIGINT NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS f_missions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source TEXT NOT NULL,
      contact TEXT NOT NULL,
      company TEXT NOT NULL,
      context TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      created_at BIGINT NOT NULL DEFAULT 0,
      UNIQUE (contact, company)
    );
    CREATE TABLE IF NOT EXISTS f_browser_tasks (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      message_id BIGINT NOT NULL UNIQUE REFERENCES f_messages(id) ON DELETE CASCADE,
      platform TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'queued',
      created_at BIGINT NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS f_radar_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source TEXT NOT NULL,
      title TEXT NOT NULL,
      text TEXT NOT NULL DEFAULT '',
      url TEXT NOT NULL DEFAULT '',
      author TEXT NOT NULL DEFAULT '',
      community TEXT NOT NULL DEFAULT '',
      domain TEXT NOT NULL DEFAULT '',
      strength TEXT NOT NULL DEFAULT 'weak',
      first_seen BIGINT NOT NULL DEFAULT 0,
      UNIQUE (source, url, title)
    );
    CREATE TABLE IF NOT EXISTS f_cost_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      model TEXT NOT NULL,
      input_tokens INTEGER NOT NULL DEFAULT 0,
      output_tokens INTEGER NOT NULL DEFAULT 0,
      est_cost REAL NOT NULL DEFAULT 0,
      ts BIGINT NOT NULL DEFAULT 0
    );

    -- ── RLS: anon/authenticated get nothing; service_role everything;
    --    sinopebase_app may browse (admin). ────────────────────────────────────
    ALTER TABLE f_agents ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_messages ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_andon_events ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_state ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_metrics ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_missions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_browser_tasks ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_radar_events ENABLE ROW LEVEL SECURITY;
    ALTER TABLE f_cost_events ENABLE ROW LEVEL SECURITY;

    DO $$
    DECLARE t TEXT;
    BEGIN
      FOREACH t IN ARRAY ARRAY[
        'f_agents','f_messages','f_andon_events','f_state','f_metrics',
        'f_missions','f_browser_tasks','f_radar_events','f_cost_events'
      ] LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I_service ON %I', t, t);
        EXECUTE format('CREATE POLICY %I_service ON %I FOR ALL TO service_role USING (true) WITH CHECK (true)', t, t);
        EXECUTE format('DROP POLICY IF EXISTS %I_admin_browse ON %I', t, t);
        EXECUTE format('CREATE POLICY %I_admin_browse ON %I FOR SELECT TO sinopebase_app USING (true)', t, t);
        EXECUTE format('GRANT ALL ON %I TO service_role', t);
        EXECUTE format('GRANT SELECT ON %I TO sinopebase_app', t);
        EXECUTE format('REVOKE ALL ON %I FROM PUBLIC', t);
        -- Default privileges may grant SELECT to anon/authenticated on new
        -- tables — strip them so the RLS policies are the only path.
        EXECUTE format('REVOKE ALL ON %I FROM anon, authenticated', t);
      END LOOP;
    END
    $$;
  `)

  // ── Atomic RPC functions ────────────────────────────────────────────────────
  // Signatures mirror the factory's TypeScript layer 1:1; policy values
  // (trust deltas, statuses, timestamps) arrive as arguments.

  await db.raw(`
    -- factory_register_agent: insert an agent, no-op on duplicate.
    CREATE OR REPLACE FUNCTION factory_register_agent(
      p_name TEXT, p_trust INTEGER, p_internal BOOLEAN, p_parent TEXT
    ) RETURNS void
    LANGUAGE plpgsql AS $$
    BEGIN
      INSERT INTO f_agents (name, trust, internal, parent)
      VALUES (p_name, p_trust, COALESCE(p_internal, false), p_parent)
      ON CONFLICT (name) DO NOTHING;
    END;
    $$;

    -- factory_queue_message: one message insert; unknown agent raises.
    CREATE OR REPLACE FUNCTION factory_queue_message(
      p_agent TEXT, p_kind TEXT, p_contact TEXT, p_copy TEXT, p_original_copy TEXT,
      p_context TEXT, p_platform TEXT, p_status TEXT, p_scheduled_at BIGINT, p_sampled BOOLEAN
    ) RETURNS TABLE(${MESSAGE_COLUMNS.replace(/\n\s+/g, ' ').trim()})
    LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM f_agents WHERE name = p_agent) THEN
        RAISE EXCEPTION 'unknown agent: %', p_agent;
      END IF;
      RETURN QUERY
        INSERT INTO f_messages (agent, kind, contact, copy, original_copy, context, platform, status, scheduled_at, sampled)
        VALUES (p_agent, p_kind, p_contact, p_copy, p_original_copy, p_context, p_platform, p_status, p_scheduled_at, p_sampled)
        RETURNING *;
    END;
    $$;

    -- factory_approve_message: atomic approve — lock, verify pending, correction
    -- metric on edit penalty, trust bump (+approved_count when unchanged),
    -- clear the reject streak, schedule.
    CREATE OR REPLACE FUNCTION factory_approve_message(
      p_id BIGINT, p_copy TEXT, p_scheduled_at BIGINT, p_delta INTEGER, p_ts BIGINT
    ) RETURNS TABLE(${MESSAGE_COLUMNS.replace(/\n\s+/g, ' ').trim()})
    LANGUAGE plpgsql AS $$
    DECLARE v_agent TEXT; v_contact TEXT;
    BEGIN
      PERFORM 1 FROM f_messages WHERE f_messages.id = p_id FOR UPDATE;
      SELECT f_messages.agent, f_messages.contact INTO v_agent, v_contact FROM f_messages
      WHERE f_messages.id = p_id AND f_messages.status = 'pending';
      IF NOT FOUND THEN
        RAISE EXCEPTION 'message % not pending', p_id;
      END IF;
      IF p_delta < 0 THEN
        INSERT INTO f_metrics (kind, agent, contact, value, ts)
        VALUES ('correction', v_agent, v_contact, p_delta, p_ts);
      END IF;
      UPDATE f_agents
      SET trust = GREATEST(0, LEAST(100, trust + p_delta)),
          approved_count = approved_count + CASE WHEN p_delta = 1 THEN 1 ELSE 0 END
      WHERE f_agents.name = v_agent;
      DELETE FROM f_state WHERE f_state.key = 'reject_streak:' || v_agent;
      UPDATE f_messages SET copy = p_copy, status = 'scheduled', scheduled_at = p_scheduled_at
      WHERE f_messages.id = p_id;
      RETURN QUERY
        SELECT * FROM f_messages WHERE f_messages.id = p_id;
    END;
    $$;

    -- factory_reject_message: atomic reject — lock, verify pending, append the
    -- reason, penalty for the creator + every ancestor (cycle-guarded), streak.
    CREATE OR REPLACE FUNCTION factory_reject_message(
      p_id BIGINT, p_reason TEXT, p_ts BIGINT,
      p_agent_penalty INTEGER, p_lineage_penalty INTEGER
    ) RETURNS TABLE(${MESSAGE_COLUMNS.replace(/\n\s+/g, ' ').trim()})
    LANGUAGE plpgsql AS $$
    DECLARE
      v_agent TEXT; v_contact TEXT; v_cur TEXT; v_parent TEXT;
      v_visited TEXT[] := ARRAY[]::TEXT[];
      v_streak TEXT;
    BEGIN
      PERFORM 1 FROM f_messages WHERE f_messages.id = p_id FOR UPDATE;
      SELECT f_messages.agent, f_messages.contact INTO v_agent, v_contact FROM f_messages
      WHERE f_messages.id = p_id AND f_messages.status = 'pending';
      IF NOT FOUND THEN
        RAISE EXCEPTION 'message % not pending', p_id;
      END IF;
      UPDATE f_messages
      SET status = 'rejected', copy = f_messages.copy || ' -- REJECTED: ' || p_reason
      WHERE f_messages.id = p_id;
      INSERT INTO f_metrics (kind, agent, contact, value, ts)
      VALUES ('rejection', v_agent, v_contact, 0, p_ts);
      v_visited := v_visited || v_agent;
      UPDATE f_agents
      SET trust = GREATEST(0, LEAST(100, trust - p_agent_penalty))
      WHERE f_agents.name = v_agent;
      v_cur := v_agent;
      LOOP
        SELECT f_agents.parent INTO v_parent FROM f_agents WHERE f_agents.name = v_cur;
        EXIT WHEN v_parent IS NULL OR v_parent = ANY(v_visited);
        v_visited := v_visited || v_parent;
        UPDATE f_agents
        SET trust = GREATEST(0, LEAST(100, trust - p_lineage_penalty))
        WHERE f_agents.name = v_parent;
        v_cur := v_parent;
      END LOOP;
      SELECT f_state.value INTO v_streak FROM f_state WHERE f_state.key = 'reject_streak:' || v_agent;
      INSERT INTO f_state (key, value)
      VALUES ('reject_streak:' || v_agent, (COALESCE(NULLIF(v_streak, ''), '0')::INTEGER + 1)::TEXT)
      ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
      RETURN QUERY
        SELECT * FROM f_messages WHERE f_messages.id = p_id;
    END;
    $$;

    -- factory_send_message: atomic send — halted check, lock, verify scheduled,
    -- mark sent, 'sent' metric (real sends only).
    CREATE OR REPLACE FUNCTION factory_send_message(
      p_id BIGINT, p_ts BIGINT
    ) RETURNS TABLE(${MESSAGE_COLUMNS.replace(/\n\s+/g, ' ').trim()})
    LANGUAGE plpgsql AS $$
    DECLARE v_agent TEXT; v_contact TEXT;
    BEGIN
      IF EXISTS (SELECT 1 FROM f_state WHERE key = 'andon' AND value = 'true') THEN
        RAISE EXCEPTION 'factory halted — no sends';
      END IF;
      PERFORM 1 FROM f_messages WHERE f_messages.id = p_id FOR UPDATE;
      SELECT f_messages.agent, f_messages.contact INTO v_agent, v_contact FROM f_messages
      WHERE f_messages.id = p_id AND f_messages.status = 'scheduled' AND f_messages.sent_at IS NULL;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'message % not sendable', p_id;
      END IF;
      UPDATE f_messages SET status = 'sent', sent_at = p_ts WHERE f_messages.id = p_id;
      INSERT INTO f_metrics (kind, agent, contact, value, ts)
      VALUES ('sent', v_agent, v_contact, 0, p_ts);
      RETURN QUERY
        SELECT * FROM f_messages WHERE f_messages.id = p_id;
    END;
    $$;

    -- factory_dryrun_send: same as send, but the metric is a SIMULATION.
    CREATE OR REPLACE FUNCTION factory_dryrun_send(
      p_id BIGINT, p_ts BIGINT
    ) RETURNS TABLE(${MESSAGE_COLUMNS.replace(/\n\s+/g, ' ').trim()})
    LANGUAGE plpgsql AS $$
    DECLARE v_agent TEXT; v_contact TEXT;
    BEGIN
      IF EXISTS (SELECT 1 FROM f_state WHERE key = 'andon' AND value = 'true') THEN
        RAISE EXCEPTION 'factory halted — no sends';
      END IF;
      PERFORM 1 FROM f_messages WHERE f_messages.id = p_id FOR UPDATE;
      SELECT f_messages.agent, f_messages.contact INTO v_agent, v_contact FROM f_messages
      WHERE f_messages.id = p_id AND f_messages.status = 'scheduled' AND f_messages.sent_at IS NULL;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'message % not sendable', p_id;
      END IF;
      UPDATE f_messages SET status = 'sent', sent_at = p_ts WHERE f_messages.id = p_id;
      INSERT INTO f_metrics (kind, agent, contact, value, ts)
      VALUES ('sent_dryrun', v_agent, v_contact, 0, p_ts);
      RETURN QUERY
        SELECT * FROM f_messages WHERE f_messages.id = p_id;
    END;
    $$;

    -- factory_pull_andon: halt + record the event in one transaction.
    CREATE OR REPLACE FUNCTION factory_pull_andon(
      p_trigger TEXT, p_detail TEXT, p_ts BIGINT, p_snapshot TEXT
    ) RETURNS TABLE(id BIGINT, trigger TEXT, detail TEXT, ts BIGINT, decision TEXT, snapshot TEXT)
    LANGUAGE plpgsql AS $$
    BEGIN
      INSERT INTO f_state (key, value) VALUES ('andon', 'true')
      ON CONFLICT (key) DO UPDATE SET value = 'true';
      RETURN QUERY
        INSERT INTO f_andon_events (trigger, detail, ts, snapshot)
        VALUES (p_trigger, p_detail, p_ts, p_snapshot)
        RETURNING f_andon_events.id, f_andon_events.trigger, f_andon_events.detail,
                  f_andon_events.ts, f_andon_events.decision, f_andon_events.snapshot;
    END;
    $$;

    -- factory_resume_andon: record the human's decision and clear the halt.
    CREATE OR REPLACE FUNCTION factory_resume_andon(
      p_event_id BIGINT, p_decision TEXT
    ) RETURNS void
    LANGUAGE plpgsql AS $$
    BEGIN
      UPDATE f_andon_events SET decision = p_decision WHERE id = p_event_id;
      UPDATE f_state SET value = 'false' WHERE key = 'andon';
    END;
    $$;

    -- factory_track_cost: one metered LLM call.
    CREATE OR REPLACE FUNCTION factory_track_cost(
      p_model TEXT, p_input_tokens INTEGER, p_output_tokens INTEGER,
      p_est_cost DOUBLE PRECISION, p_ts BIGINT
    ) RETURNS void
    LANGUAGE plpgsql AS $$
    BEGIN
      INSERT INTO f_cost_events (model, input_tokens, output_tokens, est_cost, ts)
      VALUES (p_model, p_input_tokens, p_output_tokens, p_est_cost, p_ts);
    END;
    $$;

    -- factory_sweep_upsert: one radar evidence card; dedupe on (source, url, title).
    CREATE OR REPLACE FUNCTION factory_sweep_upsert(
      p_source TEXT, p_title TEXT, p_text TEXT, p_url TEXT, p_author TEXT,
      p_community TEXT, p_domain TEXT, p_strength TEXT, p_first_seen BIGINT
    ) RETURNS TABLE(id BIGINT, source TEXT, title TEXT, text TEXT, url TEXT,
                    author TEXT, community TEXT, domain TEXT, strength TEXT, first_seen BIGINT)
    LANGUAGE plpgsql AS $$
    BEGIN
      RETURN QUERY
        INSERT INTO f_radar_events AS r (source, title, text, url, author, community, domain, strength, first_seen)
        VALUES (p_source, p_title, p_text, p_url, p_author, p_community, p_domain, p_strength, p_first_seen)
        -- No conflict target: the ONLY constraint on f_radar_events is the
        -- (source, url, title) unique — a target list cannot be qualified and
        -- bare names collide with the OUT params (42702).
        ON CONFLICT DO NOTHING
        RETURNING r.id, r.source, r.title, r.text, r.url, r.author, r.community, r.domain, r.strength, r.first_seen;
    END;
    $$;

    -- factory_plan_mission: queue the message + mark the mission planned in one
    -- transaction — a crash must not re-plan.
    CREATE OR REPLACE FUNCTION factory_plan_mission(
      p_mission_id BIGINT, p_agent TEXT, p_kind TEXT, p_contact TEXT,
      p_copy TEXT, p_context TEXT, p_platform TEXT, p_status TEXT,
      p_scheduled_at BIGINT, p_sampled BOOLEAN
    ) RETURNS TABLE(${MESSAGE_COLUMNS.replace(/\n\s+/g, ' ').trim()})
    LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM f_agents WHERE name = p_agent) THEN
        RAISE EXCEPTION 'unknown agent: %', p_agent;
      END IF;
      UPDATE f_missions SET status = 'planned' WHERE f_missions.id = p_mission_id;
      RETURN QUERY
        INSERT INTO f_messages (agent, kind, contact, copy, original_copy, context, platform, status, scheduled_at, sampled)
        VALUES (p_agent, p_kind, p_contact, p_copy, p_copy, p_context, p_platform, p_status, p_scheduled_at, p_sampled)
        RETURNING *;
    END;
    $$;

    -- factory_complete_browser_task: browser-lane send — edit penalty on the
    -- outreach agent when the copy changed, then the inline send + task done.
    CREATE OR REPLACE FUNCTION factory_complete_browser_task(
      p_task_id BIGINT, p_edited_copy TEXT, p_delta INTEGER, p_ts BIGINT
    ) RETURNS TEXT
    LANGUAGE plpgsql AS $$
    DECLARE v_task f_browser_tasks%ROWTYPE; v_msg f_messages%ROWTYPE;
    BEGIN
      SELECT * INTO v_task FROM f_browser_tasks WHERE id = p_task_id FOR UPDATE;
      IF NOT FOUND THEN
        RETURN 'browser task #' || p_task_id || ' not found';
      END IF;
      IF v_task.status <> 'queued' THEN
        RETURN 'task #' || p_task_id || ' already ' || v_task.status;
      END IF;
      SELECT * INTO v_msg FROM f_messages WHERE id = v_task.message_id FOR UPDATE;
      IF FOUND AND p_edited_copy IS NOT NULL AND p_delta < 0 THEN
        UPDATE f_agents SET trust = GREATEST(0, LEAST(100, trust + p_delta)) WHERE name = 'outreach';
        INSERT INTO f_metrics (kind, agent, contact, value, ts)
        VALUES ('correction', 'outreach', v_msg.contact, p_delta, p_ts);
      END IF;
      IF EXISTS (SELECT 1 FROM f_state WHERE key = 'andon' AND value = 'true') THEN
        RAISE EXCEPTION 'factory halted — no sends';
      END IF;
      IF NOT FOUND OR v_msg.status <> 'scheduled' OR v_msg.sent_at IS NOT NULL THEN
        RAISE EXCEPTION 'message % not sendable', v_task.message_id;
      END IF;
      UPDATE f_messages SET status = 'sent', sent_at = p_ts WHERE id = v_msg.id;
      INSERT INTO f_metrics (kind, agent, contact, value, ts)
      VALUES ('sent', v_msg.agent, v_msg.contact, 0, p_ts);
      UPDATE f_browser_tasks SET status = 'done' WHERE id = p_task_id;
      RETURN 'message #' || v_msg.id || ' marked sent'
        || CASE WHEN p_edited_copy IS NOT NULL THEN ' (edited — trust adjusted)' ELSE '' END
        || ' via browser task #' || p_task_id;
    END;
    $$;

    -- ── Aggregate helpers ─────────────────────────────────────────────────────

    -- factory_digest: the andon snapshot / dashboard counters.
    CREATE OR REPLACE FUNCTION factory_digest(p_since_ts BIGINT)
    RETURNS TABLE(sends BIGINT, dryrun_sends BIGINT, pending BIGINT, meetings BIGINT,
                  thesis_confirm BIGINT, thesis_reject BIGINT, corrections BIGINT,
                  rejections BIGINT, avg_sentiment DOUBLE PRECISION)
    LANGUAGE sql STABLE AS $$
      SELECT
        COUNT(*) FILTER (WHERE kind = 'sent') AS sends,
        COUNT(*) FILTER (WHERE kind = 'sent_dryrun') AS dryrun_sends,
        (SELECT COUNT(*) FROM f_messages WHERE status = 'pending') AS pending,
        COUNT(*) FILTER (WHERE kind = 'meeting_booked') AS meetings,
        COUNT(*) FILTER (WHERE kind = 'thesis_confirm') AS thesis_confirm,
        COUNT(*) FILTER (WHERE kind = 'thesis_reject') AS thesis_reject,
        COUNT(*) FILTER (WHERE kind = 'correction') AS corrections,
        COUNT(*) FILTER (WHERE kind = 'rejection') AS rejections,
        ROUND(AVG(value) FILTER (WHERE kind = 'sentiment')::numeric, 2)::double precision AS avg_sentiment
      FROM f_metrics WHERE ts >= p_since_ts
    $$;

    -- factory_metric_regression: trigger 4's inputs — the TS layer decides whether to pull.
    CREATE OR REPLACE FUNCTION factory_metric_regression(
      p_min_sends BIGINT, p_min_meeting_rate DOUBLE PRECISION
    ) RETURNS TABLE(sends BIGINT, meetings BIGINT, below_rate BOOLEAN)
    LANGUAGE sql STABLE AS $$
      SELECT
        COUNT(*) FILTER (WHERE kind = 'sent') AS sends,
        COUNT(*) FILTER (WHERE kind = 'meeting_booked') AS meetings,
        (COUNT(*) FILTER (WHERE kind = 'sent') >= p_min_sends
         AND COALESCE(
               COUNT(*) FILTER (WHERE kind = 'meeting_booked')::double precision
               / NULLIF(COUNT(*) FILTER (WHERE kind = 'sent'), 0), 0) < p_min_meeting_rate
        ) AS below_rate
      FROM f_metrics
    $$;

    -- factory_browser_tasks: the Firefox-plugin lane's queued work.
    CREATE OR REPLACE FUNCTION factory_browser_tasks()
    RETURNS TABLE(id BIGINT, message_id BIGINT, platform TEXT, status TEXT,
                  contact TEXT, copy TEXT, context TEXT)
    LANGUAGE sql STABLE AS $$
      SELECT bt.id, bt.message_id, bt.platform, bt.status, m.contact, m.copy, m.context
      FROM f_browser_tasks bt JOIN f_messages m ON m.id = bt.message_id
      WHERE bt.status = 'queued' ORDER BY bt.id
    $$;

    -- factory_trust_gate_lookup: the trust gate's copy check (pending/rejected only).
    CREATE OR REPLACE FUNCTION factory_trust_gate_lookup(p_text TEXT)
    RETURNS TABLE(status TEXT)
    LANGUAGE sql STABLE AS $$
      SELECT status FROM f_messages
      WHERE status IN ('pending', 'rejected') AND strpos(p_text, copy) > 0
      LIMIT 1
    $$;

    -- factory_month_stats: the budget meter + CAC math inputs (aggregates have
    -- no PostgREST equivalent, so they ride the rpc channel too).
    CREATE OR REPLACE FUNCTION factory_month_stats(p_start_ts BIGINT)
    RETURNS TABLE(spend DOUBLE PRECISION, meetings BIGINT)
    LANGUAGE sql STABLE AS $$
      SELECT
        ROUND(COALESCE((SELECT SUM(est_cost) FROM f_cost_events WHERE ts >= p_start_ts), 0)::numeric, 4)::double precision AS spend,
        (SELECT COUNT(*) FROM f_metrics WHERE kind = 'meeting_booked' AND ts >= p_start_ts) AS meetings
    $$;

    -- factory_mission_seed: one mission insert; dedupe on (contact, company).
    CREATE OR REPLACE FUNCTION factory_mission_seed(
      p_source TEXT, p_contact TEXT, p_company TEXT, p_context TEXT
    ) RETURNS TABLE(id BIGINT, source TEXT, contact TEXT, company TEXT, context TEXT, status TEXT)
    LANGUAGE plpgsql AS $$
    BEGIN
      RETURN QUERY
        INSERT INTO f_missions AS m (source, contact, company, context)
        VALUES (p_source, p_contact, p_company, p_context)
        -- No conflict target: the ONLY constraint is UNIQUE (contact, company)
        -- and a target list cannot be qualified (42702, see sweep).
        ON CONFLICT DO NOTHING
        RETURNING m.id, m.source, m.contact, m.company, m.context, m.status;
    END;
    $$;

    -- factory_state_set: key/value upsert (f_state's PK is "key", not "id").
    CREATE OR REPLACE FUNCTION factory_state_set(p_key TEXT, p_value TEXT)
    RETURNS void
    LANGUAGE plpgsql AS $$
    BEGIN
      INSERT INTO f_state (key, value) VALUES (p_key, p_value)
      ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
    END;
    $$;

    -- factory_reply_once: a reply is recorded once per contact, ever
    -- (codex finding 7) — the conditional insert must be atomic.
    CREATE OR REPLACE FUNCTION factory_reply_once(p_contact TEXT, p_ts BIGINT)
    RETURNS void
    LANGUAGE plpgsql AS $$
    BEGIN
      INSERT INTO f_metrics (kind, agent, contact, value, ts)
      SELECT 'reply', 'outreach', p_contact, 0, p_ts
      WHERE NOT EXISTS (SELECT 1 FROM f_metrics WHERE kind = 'reply' AND contact = p_contact);
    END;
    $$;

    -- EXECUTE is granted to service_role only; the sinopebase_revoke_fn_execute
    -- event trigger strips PUBLIC from every function created above.
    GRANT EXECUTE ON FUNCTION factory_register_agent(text, integer, boolean, text) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_queue_message(text, text, text, text, text, text, text, text, bigint, boolean) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_approve_message(bigint, text, bigint, integer, bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_reject_message(bigint, text, bigint, integer, integer) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_send_message(bigint, bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_dryrun_send(bigint, bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_pull_andon(text, text, bigint, text) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_resume_andon(bigint, text) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_track_cost(text, integer, integer, double precision, bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_sweep_upsert(text, text, text, text, text, text, text, text, bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_plan_mission(bigint, text, text, text, text, text, text, text, bigint, boolean) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_complete_browser_task(bigint, text, integer, bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_digest(bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_metric_regression(bigint, double precision) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_browser_tasks() TO service_role;
    GRANT EXECUTE ON FUNCTION factory_trust_gate_lookup(text) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_month_stats(bigint) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_mission_seed(text, text, text, text) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_state_set(text, text) TO service_role;
    GRANT EXECUTE ON FUNCTION factory_reply_once(text, bigint) TO service_role;
  `)
}
