/**
 * File Store Backup Utility
 *
 * Backs up and restores all buckets and objects from an IFileStore
 * to/from a local directory with a manifest.json.
 */

import { existsSync } from 'node:fs'
import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import type { IFileStore } from '~/tools/filesystem/store-interface'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Per-object entry in the backup manifest. */
export interface ManifestEntry {
  /** Bucket name. */
  bucket: string
  /** Object path within the bucket. */
  path: string
  /** File name on disk in the backup directory. */
  fileName: string
}

/** Structure of the backup manifest JSON file. */
export interface BackupManifest {
  /** Timestamp when the backup was created. */
  createdAt: string
  /** Array of backed-up file entries. */
  files: ManifestEntry[]
}

// ---------------------------------------------------------------------------
// backupFileStore
// ---------------------------------------------------------------------------

/**
 * Copy all buckets and objects from an IFileStore to a local backup directory.
 *
 * Writes a manifest.json alongside the files describing what was backed up.
 *
 * @param sourceStore - The file store to back up.
 * @param backupDir   - Local directory to write backup files into.
 * @returns The backup manifest.
 */
export async function backupFileStore(
  sourceStore: IFileStore,
  backupDir: string,
): Promise<BackupManifest> {
  // Ensure the backup directory exists
  if (!existsSync(backupDir)) {
    await mkdir(backupDir, { recursive: true })
  }

  const filesDir = join(backupDir, 'files')
  if (!existsSync(filesDir)) {
    await mkdir(filesDir, { recursive: true })
  }

  const manifest: BackupManifest = {
    createdAt: new Date().toISOString(),
    files: [],
  }

  const buckets = await sourceStore.listBuckets()
  let fileCounter = 0

  for (const bucket of buckets) {
    const objects = await sourceStore.list(bucket.name)

    for (const obj of objects) {
      fileCounter++
      const ext = obj.name.includes('.') ? obj.name.split('.').pop() : ''
      const fileName = ext ? `file_${fileCounter}.${ext}` : `file_${fileCounter}`

      try {
        const data = await sourceStore.read(bucket.name, obj.name)
        const outputPath = join(filesDir, fileName)
        await Bun.write(outputPath, data)

        manifest.files.push({
          bucket: bucket.name,
          path: obj.name,
          fileName,
        })
      } catch {
        // Skip objects that can't be read
      }
    }
  }

  // Write manifest
  const manifestPath = join(backupDir, 'manifest.json')
  await Bun.write(manifestPath, JSON.stringify(manifest, null, 2))

  return manifest
}

// ---------------------------------------------------------------------------
// restoreFileStore
// ---------------------------------------------------------------------------

/**
 * Restore all buckets and objects from a local backup directory back into
 * an IFileStore.
 *
 * Reads the manifest.json generated by backupFileStore.
 *
 * @param targetStore - The file store to restore into.
 * @param backupDir   - Local directory containing the backup data.
 */
export async function restoreFileStore(targetStore: IFileStore, backupDir: string): Promise<void> {
  const manifestPath = join(backupDir, 'manifest.json')
  if (!existsSync(manifestPath)) {
    throw new Error(`Backup manifest not found: ${manifestPath}`)
  }

  const manifestRaw = await Bun.file(manifestPath).text()
  const manifest: BackupManifest = JSON.parse(manifestRaw)

  const filesDir = join(backupDir, 'files')

  // Restore using a unique set of buckets to avoid redundant ensureBucket calls
  const ensuredBuckets = new Set<string>()

  for (const entry of manifest.files) {
    if (!ensuredBuckets.has(entry.bucket)) {
      await targetStore.ensureBucket(entry.bucket)
      ensuredBuckets.add(entry.bucket)
    }

    const filePath = join(filesDir, entry.fileName)
    try {
      const data = await Bun.file(filePath).arrayBuffer()
      await targetStore.save(entry.bucket, entry.path, data)
    } catch {
      // Skip files that can't be restored
    }
  }
}
