/**
 * Migration file templates — used when generating new migration files.
 *
 * Port of PocketBase's plugins/migratecmd/templates.go (Go -> TypeScript).
 * Layer 5 -- provides code generation for migration files.
 */

/**
 * Returns the TypeScript source code for a new empty migration file.
 *
 * @param migrationName - The unique name for this migration (e.g. timestamp).
 * @returns TypeScript source code as a string.
 */
export function migrationTemplate(migrationName: string): string {
  return `/**
 * Migration: ${migrationName}
 *
 * Auto-generated by Sinopebase migrate create.
 */
import type { MigrationDB } from '../migrations/types.ts'

export async function up(db: MigrationDB): Promise<void> {
  // TODO: write your migration SQL here
  // Example:
  // await db.raw(\`
  //   CREATE TABLE IF NOT EXISTS my_table (
  //     id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  //     name TEXT NOT NULL DEFAULT ''
  //   )
  // \`)
}

export async function down(db: MigrationDB): Promise<void> {
  // TODO: write your rollback SQL here
  // Example:
  // await db.raw('DROP TABLE IF EXISTS my_table')
}
`
}

/**
 * Returns a JavaScript-compatible migration template (without TypeScript types).
 *
 * @param migrationName - The unique name for this migration.
 * @returns JavaScript source code as a string.
 */
export function migrationTemplateJS(migrationName: string): string {
  return `/**
 * Migration: ${migrationName}
 *
 * Auto-generated by Sinopebase migrate create.
 */

/** @param {import('../migrations/types.ts').MigrationDB} db */
export async function up(db) {
  // TODO: write your migration SQL here
}

/** @param {import('../migrations/types.ts').MigrationDB} db */
export async function down(db) {
  // TODO: write your rollback SQL here
}
`
}

/**
 * Returns the file name for a migration file.
 *
 * @param migrationName - The unique name for this migration.
 * @param useTs - Whether to use .ts extension (default: true).
 * @returns The file name including extension.
 */
export function migrationFileName(
  migrationName: string,
  useTs: boolean = true,
): string {
  const ext = useTs ? '.ts' : '.js'
  return `${migrationName}${ext}`
}
